excluded:
  - Pods
  - SwiftHookDemo
  - SwiftHookSPMDemo

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - identifier_name
  - cyclomatic_complexity
  - large_tuple
  - inclusive_language
  - block_based_kvo
