included:
  - SwiftHook

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - cyclomatic_complexity
  - large_tuple
  - inclusive_language
  - block_based_kvo
  - file_length