excluded:
  - Pods

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - todo
  - identifier_name
  - function_parameter_count
  - type_body_length
  - file_length
  - cyclomatic_complexity