disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - identifier_name
  - cyclomatic_complexity
  - large_tuple
  - inclusive_language
  - block_based_kvo
  - function_parameter_count
  - xctfail_message
  - file_length
  - type_body_length